name: Build and test

on: push

env:
  build_dir: build
  build_config: Release
  cflags_gnuc: -Werror
  cflags_msvc: /wd5105 /WX
  test_target: cowl-test
  docs_target: cowl-docs
  examples_target: cowl-examples

jobs:
  build:
    name: Build and test
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure runner
      run: |
        if [ $RUNNER_OS == 'Windows' ]; then
          echo 'cflags="${{env.cflags_msvc}}"' >> $GITHUB_ENV
          echo 'config_subdir=./${{env.build_config}}' >> $GITHUB_ENV
          choco install winflexbison3
        else
          echo 'cflags="${{env.cflags_gnuc}}"' >> $GITHUB_ENV
          echo 'config_subdir=.' >> $GITHUB_ENV
          if [ $RUNNER_OS == 'macOS' ]; then
            brew install flex bison
            echo '/usr/local/opt/bison/bin' >> $GITHUB_PATH
            echo '/usr/local/opt/flex/bin' >> $GITHUB_PATH
          fi
        fi
      shell: bash

    - name: Configure CMake
      run: >
        cmake -B ${{env.build_dir}}
        -DULIB_LEAKS=ON
        -DCMAKE_BUILD_TYPE=${{env.build_config}}
        -DCMAKE_C_FLAGS=${{env.cflags}}

    - name: Build
      run: >
        cmake --build ${{env.build_dir}}
        --config ${{env.build_config}}
        --target ${{env.test_target}} ${{env.examples_target}}

    - name: Run examples
      working-directory: ${{env.build_dir}}/examples
      run: ${{env.config_subdir}}/*-example*
      shell: bash

    - name: Run tests
      working-directory: ${{env.build_dir}}/test
      run: ${{env.config_subdir}}/${{env.test_target}}

  docs:
    name: Generate the documentation
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Configure runner
        run: |
          brew install doxygen
          pip3 install -U Sphinx sphinx-rtd-theme breathe

      - name: Build docs
        run: |
          cmake -B ${{env.build_dir}} -DCOWL_PARSERS=''
          cmake --build ${{env.build_dir}} --target ${{env.docs_target}}
